const mild = new Map([
    [1,"A puddle of grease appears where you are standing, with a 10-foot radius. You and anyone within 10 feet of you must make a Dexterity check at your spell save DC or fall prone."],
    [2,"You levitate 6 inches off the ground for 1 minute."],
    [3,"You gain tremorsense with a range of 30 feet for 1 minute."],
    [4,"You make no sounds for 1 minute and you gain advantage on any Dexterity (Stealth) checks."],
    [5,"You grow a beard made of feathers, which remains until you sneeze."],
    [6,"You can\'t speak for 1 minute. When you try, pink bubbles float out of your mouth."],
    [7,"You are immune to intoxication for the next 5d6 days. You rolled a:5d6"],
    [8,"For the next minute, you must shout when you speak."],
    [9,"Illusory butterflies and flower petals flutter in the air around you in a 10-foot radius for 1 minute."],
    [10,"You cast mirror image on yourself, which lasts for 1 minute and does not require concentration."],
    [11,"You are surrounded by faint, ethereal music for 1 minute."],
    [12,"You regain all expended rages."],
    [13,"Your hair grows to double its current length over the next minute."],
    [14,"Your hair falls out but grows back within 1 day."],
    [15,"You gain the ability to speak one additional language of your choice for 1 hour."],
    [16,"You are invisible for 1 minute."],
    [17,"Your eyes permanently change color. If they are a blue or gray shade, they turn dark brown, or vice versa. A spell such as remove curse can end this effect."],
    [18,"Small birds flutter and chirp in your vicinity for 1 minute, during which time you automatically fail any Stealth check."],
    [19,"You feel the incredible urge to relieve yourself. Until you do, your Strength and Intelligence are reduced by 1. If you don\'t relieve yourself in the next 2 minutes, the above effects are removed, but your Charisma score is reduced by 4 for 1 hour or until you change your trousers."],
    [20,"Gnats buzz around your head for 1 minute, distracting you. You must make a Constitution saving throw against your own spell save DC to make any attack"],
    [21,"You are surrounded by a faint, offensive odor for 1 minute. You gain disadvantage on all Charisma checks."],
    [22,"For the next minute, all attacks require 2 consecutive actions to make."],
    [23,"You have the irresistible urge to scratch an itch in the middle of your back, just out of reach, for 1 minute. If you don\'t scratch it using a back scratcher or some similar device , you must succeed a Constitution saving throw against your spell save DC to cast a spell."],
    [24,"You have a momentary vision of your own death. If you fail a Wisdom saving roll at your spell DC, you are frightened for 1 minute."],
    [25,"Your Charisma is increased by 2 for 1 minute."],
    [26,"Over the next minute, all plants within 20 feet of you grow as if affected by the plant growth spell"],
    [27,"Your eyes glow red for 1 minute."],
    [28,"Your Constitution is increased by 2 for 1 minute."],
    [29,"You add your proficiency bonus to all Charisma checks for the next hour, if you don\'t already add it."],
    [30,"For the next minute, you have advantage on the next roll you make where you don\'t already have advantage."],
    [31,"Every creature within 15 feet of you takes 1 necrotic damage. If you are wounded, you regain hit points up to the amount of damage dealt. If you are not wounded, you gain this amount of temporary hit points."],
    [32,"A magic mouth appears on a nearby wall or flat surface. When you speak, your voice comes from the magic mouth. This lasts for 1 minute."],
    [33,"You can hear exceptionally well for 1 minute, gaining advantage for all Perception checks related to sound."],
    [34,"You lose the ability to smell for 1 hour."],
    [35,"For the next day, each time you say a word with the \'s\' sound, it sounds like a hissing snake."],
    [36,"A gentle gust of wind blows outward from you. All creatures within 40 feet of you can feel it, but it otherwise does nothing."],
    [37,"Your Dexterity is increased by 2 for 1 minute."],
    [38,"You immediately take 1d10 radiant damage. You rolled a:1d10"],
    [39,"One randomly-chosen non-magical item in your possession that weighs 1 pound or less vanishes and is forever gone."],
    [40,"Your Wisdom is increased by 2 for 1 minute."],
    [41,"You immediately gain 10 temporary hit points."],
    [42,"3d6 silver pieces appear near you. You rolled a:3d6"],
    [43,"You regain 5 hit points per round for 1 minute."],
    [44,"An imp appears near you. Make a Charisma saving throw against your spell save DC. If you succeed, the imp is subservient, otherwise, it is hostile. The imp, if not banished or defeated, vanishes after 1 hour."],
    [45,"Your speed is increased by 10 feet for 1 minute."],
    [46,"You gain proficiency on all Strength checks for the next hour, if you don\'t already have it."],
    [47,"Your Intelligence is increased by 2 for 1 minute."],
    [48,"One randomly-chosen non-magical item in your possession that weighs 1 pound or less is duplicated."],
    [49,"Mushrooms sprout around you in a 5-foot radius and vanish after 1 minute. If one is harvested and eaten within this time, the creature must make a Constitution saving throw against your spell save DC. On a failed save, it takes 5d6 poison damage. On successful one, it gains 5d6 temporary hit points."],
    [50,"You can smell exceptionally well for 1 minute, gaining blindsight with a radius of 10 feet and advantage on all Perception checks related to odor."],
    [51,"Your feet sink into the ground, making you completely immobile for one minute. This has no effect if you were not standing on the ground when the spell was cast."],
    [52,"One random gem worth 100gp appears near you."],
    [53,"For the next minute, you have double vision. This gives you disadvantage on ranged attacks (including spell attacks) and Perception checks involving sight."],
    [54,"You are surrounded by a faint, pleasant odor. You gain advantage on all Charisma checks you make within the next minute."],
    [55,"You lose proficiency on all skill checks for 1 minute."],
    [56,"You gain freedom of movement for 1 minute."],
    [57,"You gain darkvision with a radius of 60 feet for 1 minute. If you already have darkvision, you lose it for 1 minute."],
    [58,"Approximately 100 gallons of water appear over your head and those within 10 feet of you, evenly distributed above everybody within the radius."],
    [59,"You gain a +1 to your AC for one minute."],
    [60,"You fall victim to a horrible cramp in both legs, reducing your speed by 10 feet for 1 hour."],
    [61,"For the next hour, you are unable to read as the letters all appear jumbled."],
    [62,"For the next day, everything you say must rhyme. If it doesn\'t, you take 1d6 psychic damage."],
    [63,"During the next hour, you may re-roll any one save, attack roll, or skill check. If you do, you must take the new roll\'s result."],
    [64,"You grow 1d6 inches in height. You gradually return to your original height over the course of 1 day. You rolled a:1d6"],
    [65,"You immediately take 2d4 psychic damage. You rolled a:2d4"],
    [66,"For the next hour, any time you make an ability check, roll 1d4 and subtract the result."],
    [67,"You gain the ability to speak with animals for one hour."],
    [68,"You gain a -1 penalty to your AC for 1 minute."],
    [69,"You gain the use of an unseen servant for 1 hour."],
    [70,"A bad joke comes to mind and until you tell it (which takes an entire action), you suffer a Wisdom penalty of 1."],
    [71,"You hear a ringing in your ears for 1 minute. During this time, making an attack requires a Constitution check against your spell save DC."],
    [72,"You lose 1d6x5 pounds. You gradually return to your original weight over the course of 1 day. You rolled a:1d6"],
    [73,"Your clothes become dirty and filthy. Until you can change and/or clean your clothes, your Charisma is reduced by 1."],
    [74,"You gain proficiency in Wisdom checks for the next hour, if you don\'t already have it."],
    [75,"You shrink 1d6 inches in height. You gradually return to your original height over the course of 1 day. You rolled a:1d6"],
    [76,"Your skin permanently darkens as if you have a tan, or if you are already dark-skinned, your skin becomes one shade lighter. A spell such as remove curse can end this effect."],
    [77,"For 1 minute, one creature of your choice within 30 feet of you gains a -1 penalty to attack rolls, damage rolls, and their AC."],
    [78,"For the next hour, any time you make an ability check, roll 1d4 and add the result."],
    [79,"If you perform an action that requires a saving throw within the next minute, the target gains disadvantage on its saving throw."],
    [80,"Your Strength is increased by 2 for 1 minute."],
    [81,"One creature of your choice gains a +1 bonus to attack rolls, damage rolls, and its AC for 1 minute."],
    [82,"You immediately heal 2d10 hit points. You rolled a:2d10"],
    [83,"You gain proficiency on all Intelligence checks for the next hour, if you don\'t already have it."],
    [84,"You gain 1d6x10 pounds. You gradually return to your original weight over the course of 1 day. You rolled a:1d6"],
    [85,"You gain proficiency in all Dexterity checks for the next hour, if you don\'t already have it."],
    [86,"Your fingernails and toenails grow to an uncomfortable length. Until you trim them, your Dexterity is reduced by 1 and your speed is reduced by 5 feet, even if you\'re not wearing shoes."],
    [87,"You gain the effects of the blur spell for 1 minute, which does not require concentration to maintain."],
    [88,"For the next hour, you appear to others to be the opposite gender."],
    [89,"You gain the service of a 2nd-level spiritual weapon for 1 minute."],
    [90,"You gain proficiency in all Constitution checks for the next hour, if you don\'t already have it."],
    [91,"Every inanimate object that isn't being worn or carried within 40 feet of you becomes enshrouded with shadows for 1 minute. Enshrouded objects are considered heavily obscured."],
    [92,"Your fingers become sore for 1 hour. During this time, you must succeed on a Dexterity saving throw against your spell save DC to perform a sleight of hand check."],
    [93,"You feel extremely nauseated. Make a Constitution saving throw against your spell save DC. If you fail, you must spend your next action throwing up."],
    [94,"You immediately lose one unspent rage."],
    [95,"For the next hour, each child you come across thinks that you are their parent and cannot be convinced otherwise."],
    [96,"For the next minute, you have an uncontrollable desire to dance, you must succeed on a wisdom saving throw each time that you want to perform an action. On a failed save, you spend your turn performing your best dance moves."],
    [97,"For the next minute, you become a pacifist and must spend your turn trying to calm everyone down and to resolve your quarrel peacefully. A spell such as remove curse can end this affliction early."],
    [98,"One ally of your choice within 30ft must make a wisdom saving throw, on a failed save for the next minute they become infatuated with you and will do anything they can stop you from coming to harm."],
    [99,"You feel tired, on your next turn you must spend your action by laying down and having a nap. During this time you are prone."],
    [100,"For the next hour, you must refer to yourself in the third person as someone named 'Lady Branthwaite'"]
])
exports.mild = mild; //Make the array available to use in other files