const moder = new Map([
    [1,"For the next day, your skin tone changes color every 30 minutes, cycling through the colors of the rainbow."],
    [2,"You are confused for 1 minute, as though you were affected by the confusion spell."],
    [3,"Your Strength is increased by 2 for 1 day."],
    [4,"A third eye appears in your forehead, giving you advantage on sight-based Wisdom (Perception) checks for 1 minute."],
    [5,"The next attack that you make within the next minute that does damage, the damage is maximized."],
    [6,"For the next minute, you can teleport up to 20 feet as part of your movement on each of your turns."],
    [7,"You become intoxicated for 2d6 hours. You rolled a:2d6"],
    [8,"Your Intelligence is decreased by 2 for 1 day."],
    [9,"Your Wisdom is increased by 2 for 1 day."],
    [10,"For 1 minute, any flammable item you touch, that you aren't already wearing or carrying, bursts into flame."],
    [11,"Plants grow around you and you are restrained for 1 minute."],
    [12,"A random creature within 30 feet of you gains a flying speed equal to its walking speed for 1 minute."],
    [13,"You may immediately take 1 additional action."],
    [14,"If you fall within the next day, you automatically have the benefit of the feather fall spell."],
    [15,"For the next attack that you make within 1 minute that does damage, the damage is minimized."],
    [16,"You are surrounded by a spectral shield for 1 minute, giving you a +2 bonus to your AC and immunity to magic missile."],
    [17,"You and all creatures within 30 feet of you gain vulnerability to piercing damage for 1 minute."],
    [18,"For 1 minute, you gain resistance to nonmagical bludgeoning, piercing, and slashing damage."],
    [19,"You are protected from Elementals for 1 hour. Such creatures can't attack you or harm you unless they succeed on a Charisma saving throw against your spell save DC."],
    [20,"For the next minute, one creature of your choice gets a -2 penalty to its AC, attack rolls, and damage rolls."],
    [21,"You and all creatures within 30 feet of you gain vulnerability to bludgeoning damage for 1 minute."],
    [22,"You emanate light in a 30-foot radius for 1 minute. Any creature within 5 feet of you that can see is blinded until the end of its next."],
    [23,"For the next hour, you gain advantage on Charisma checks when dealing with any creature wearing black, but disadvantage if they are wearing white. If they are wearing both, this doesn't apply."],
    [24,"You are protected from Plants for 1 hour. Such creatures can't attack you or harm you unless they succeed on a Charisma saving throw against your spell save DC."],
    [25,"Your Intelligence is increased by 2 for 1 day."],
    [26,"Within the next hour, you have advantage on the next roll you make where you don't already have advantage."],
    [27,"You gain a +2 bonus to your AC for 1 minute."],
    [28,"For the next minute, you are in the Border Ethereal near the location you were last in."],
    [29,"For the next minute, you gain resistance to thunder and force damage."],
    [30,"An imp appears within 30 feet of you. Make a Charisma saving throw against your spell save DC. If you succeed, the imp is subservient, otherwise, it is hostile. The imp, if not banished or defeated, vanishes after 1 day."],
    [31,"For the next minute, you gain resistance to fire and cold damage."],
    [32,"For the next hour, you gain advantage on Charisma checks when dealing with any creature wearing red, but disadvantage if they are wearing green. If they are wearing both, this doesn't apply."],
    [33,"You gain the service of an arcane eye for 1 minute that does not require concentration."],
    [34,"You lose the ability to smell for 1 day."],
    [35,"You gain a -2 penalty to your AC for 1 minute."],
    [36,"You and all creatures within 30 feet of you gain vulnerability to necrotic damage for 1 minute."],
    [37,"You become invisible and silent for 1 minute."],
    [38,"Your Dexterity is increased by 2 for 1 day."],
    [39,"You can detect the thoughts of 1 creature you can see within 30 feet of you for 1 minute."],
    [40,"For the next minute, all melee attacks you make with a non-magical weapon gain a +1 bonus to hit and to damage, and are considered magical for the purpose of overcoming resistances."],
    [41,"Your Strength is decreased by 2 for 1 hour."],
    [42,"You gain freedom of movement for 1 day."],
    [43,"Your Dexterity is decreased by 2 for 1 hour."],
    [44,"You are affected by a faerie fire spell for 1 minute. You automatically fail the saving throw."],
    [45,"You are protected from Beasts for 1 hour. Such creatures can't attack you or harm you unless they succeed a Charisma saving throw against your spell save DC."],
    [46,"3d6 gold pieces appear near you. You rolled a:3d6"],
    [47,"For 2d6 hours, you have a faint pink glow. Anyone trying to perceive you has advantage on their Perception check. You rolled a:2d6"],
    [48,"For the next minute, light and darkness quickly alternate around you in a 30-foot radius, creating a strobe effect. Sight-based creatures gain a -1 penalty on attack rolls against you and Perception checks against you, and you gain a +1 bonus to Stealth checks."],
    [49,"You and all creatures within 30 feet of you gain vulnerability to slashing damage for 1 minute."],
    [50,"All creatures within 20 feet of you must make a Strength saving throw against your spell save DC or be knocked prone."],
    [51,"You are protected from Undead for one hour. Such creatures can't attack you or harm you unless they succeed on a Charisma saving throw against your spell save DC."],
    [52,"For the next minute, you can pass through any solid, non-magical wall that is 6 or fewer inches thick."],
    [53,"You are protected from Fiends for one hour. Such creatures can't attack you or harm you unless they succeed on a Charisma save against your spell save DC."],
    [54,"You permanently gain one 1st-level spell slot but forget one cantrip that you already know. A spell such as remove curse can end this effect."],
    [55,"You immediately gain 15 temporary hit points."],
    [56,"All gold you are carrying is now silver."],
    [57,"For the next minute, you gain resistance to necrotic and radiant damage."],
    [58,"You are at the center of a fog cloud spell which lasts for 1 minute."],
    [59,"Your Charisma is increased by 2 for 1 day."],
    [60,"You and all creatures within 30 feet of you gain vulnerability to lightning damage for 1 minute."],
    [61,"You and all creatures within 30 feet of you gain vulnerability to force damage for 1 minute."],
    [62,"For the next minute, any creature you touch takes 2d6 lightning damage."],
    [63,"You are surrounded by a horrible, noxious odor for 1 minute. Anyone within 10 feet of you must make a Constitution saving throw or be stunned."],
    [64,"Your Charisma is decreased by 2 for 1 hour."],
    [65,"You gain the service of a phantom steed for 1 day."],
    [66,"You and all creatures within 30 feet of you gain vulnerability to acid damage for 1 minute."],
    [67,"Your Wisdom is decreased by 2 for 1 hour."],
    [68,"Your speed is increased by 10 feet for 1 day."],
    [69,"You gain the ability to walk on water for 1 day."],
    [70,"You and all creatures within 30 feet of you gain vulnerability to psychic damage for 1 minute."],
    [71,"One creature of your choice gets a +2 bonus to all attack rolls, damage rolls, and their armor class AC for 1 minute."],
    [72,"You lose proficiency in one randomly chosen skill, tool, or weapon type for 2d6 days. You rolled a:2d6"],
    [73,"All food and drink within 30 feet of you becomes putrid, spoiled, or rotten. Consuming this food deals 2d6 poison damage and causes the poisoned condition for 1 hour."],
    [74,"All silver you are carrying is now copper."],
    [75,"You and all creatures within 30 feet of you gain vulnerability to fire damage for 1 minute."],
    [76,"You lose proficiency in all skill rolls for 1d4 hours. You rolled a:1d4"],
    [77,"You are protected from Fey for one hour. Such creatures can't attack you or harm you unless they succeed on a Charisma saving throw against your spell save DC."],
    [78,"For the next hour, any time you make an ability check, roll 1d6 and subtract the result."],
    [79,"For the next minute, you gain resistance to poison and psychic damage."],
    [80,"You\'re feeling lucky. For the next hour, any time you make an ability check, roll 1d6 and add the result."],
    [81,"You immediately take 2d6 psychic damage. You rolled a:2d6"],
    [82,"You gain proficiency in one skill of your choice that you're not already proficient in for one hour."],
    [83,"Your Constitution is increased by 2 for 1 day."],
    [84,"You and all creatures within 30 feet of you gain vulnerability to thunder damage for 1 minute."],
    [85,"You and all creatures within 30 feet of you gain vulnerability to cold damage for 1 minute."],
    [86,"You gain the ability to speak one language of your choice for 1 day."],
    [87,"You and all creatures within 30 feet of you gain vulnerability to radiant damage for 1 minute."],
    [88,"You are protected from Celestials for 1 hour. Such creatures can't attack you or harm you unless they succeed on a Charisma saving throw against your spell save DC."],
    [89,"For the next minute, you are to perform an action that causes damage of any type."],
    [90,"You gain spider climb for 1 minute, and it does not require concentration to maintain."],
    [91,"You immediately lose all unspent rages and may not regain them until you have finished a long rest."],
    [92,"You and all creatures within 30 feet of you gain vulnerability to poison damage for 1 minute."],
    [93,"You gain the ability to speak with animals for 1 day."],
    [94,"All food and drink within 30 feet of you is purified."],
    [95,"You are protected from Aberrations for 1 hour. Such creatures can't attack you or harm you unless they succeed on a Charisma saving throw against your spell save DC."],
    [96,"All your clothing and equipment teleports to the nearest open space at least 15 feet from you that you can see."],
    [97,"Your Constitution is decreased by 2 for 1 hour."],
    [98,"On your next attack that hits, your target is antagonized by you, as if afflicted by the antagonize spell."],
    [99,"For the next minute, you forget how to walk and must crawl everywhere, your movement speed is halved."],
    [100,"You lose 2d6 hp, one of your allies of your choice within 30ft gains the same amount of hp as temporary hit points. You rolled a:2d6"]
]);

exports.moder = moder; //Make the array available to use in other files